server:
  port: 8080
spring:
  application:
    name: fleet-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${hm.db.host}:5433/Fleet
    username: postgres
    password: ${hm.db.pw}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true